image: node:18.12.1

before_script:
  ##
  ## Install ssh-agent if not already installed, it is required by Docker.
  ## (change apt-get to yum if you use an RPM-based image)
  ##
  - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'

  ##
  ## Run ssh-agent (inside the build environment)
  ##
  - eval $(ssh-agent -s)

  ##
  ## Give the right permissions, otherwise ssh-add will refuse to add files
  ## Add the SSH key stored in SSH_PRIVATE_KEY file type CI/CD variable to the agent store
  ##
  - chmod 400 "$LANTER_SSH_PRIVATE_KEY"
  - ssh-add "$LANTER_SSH_PRIVATE_KEY"

  ##
  ## Create the SSH directory and give it the right permissions
  ##
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

cache:
  paths:
    - node_modules/

stages:
  - setup
  - deploy

# 1) Install the modules and build the NextJS Website
setup:
  stage: setup
  script:
    - echo "$ENVIRONMENT_VARIABLES" >> ".env"
    - npm ci
    - npm run build

# 2) Deploy to private server (copying over the .next/server)
deploy:
  stage: deploy
  # Talk to the server
