stages:          # List of stages for jobs, and their order of execution
  - build main
 
build-job main:       
  stage: build main
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."
    - sudo mkdir /opt/test123
  only :
     - main 
