## Cache node modules
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .next/cache/

## Artifact the .next directory
default:
  artifacts:
    expire_in: 5 min
    paths:
      - .next/

## Define the stages
stages:
  - build
  # - deploy

build:
  stage: build
  image: node:latest
  script:
    ## Add the environment variables and echo it to a .env file for building
    - echo "$ENVIRONMENT_VARIABLES" >> ".env"
    ## Install
    - npm ci 
    ## Build
    - npm run build
  only:
    - master
# deploy:
#   stage: deploy
#   script:
#     ## Transfer relevant NextJS files to the server
#     - rsync -az next.config.js gitlab@20.157.214.14:/opt/whsp/
#     - rsync -az package.json gitlab@20.157.214.14:/opt/whsp/
#     - rsync -az node_modules gitlab@20.157.214.14:/opt/whsp/
#     - rsync -az .next gitlab@20.157.214.14:/opt/whsp/
#     ## Restart the server
#     - ssh -tt gitlab@20.157.214.14 "sudo systemctl restart nextjs"
#   only:
#     - master