image: node:18.12.1

cache:
  paths:
    - node_modules/

stages:
  - setup
  - deploy

# 1) Install the modules and build the NextJS Website
setup:
  stage: setup
  script:
    - echo "$ENVIRONMENT_VARIABLES" >> ".env"
    - npm ci
    - npm run build

# 2) Deploy to private server (copying over the .next/server)
deploy:
  stage: deploy
