default:
  artifacts:
    expire_in: 5 min
    paths:
      - .next/

## Define the stages
stages:
  - build
  # - deploy

build:
  stage: build
  script:
    # - node -v
    - npm -v
    ## Add the environment variables and echo it to a .env file for building
    - echo "$ENVIRONMENT_VARIABLES" >> ".env"
    ## Install
    - npm ci
    ## Build
    - npm run build
  only:
    - master