image: node:18.12.1

cache:
  paths:
    - node_modules/

stages:
  - install
  - build

install:
  stage: install
  script:
    - npm install --global

build:
  stage: build
  script:
    - npm run build
